steps:

- id: 'Run unit tests'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '.']
  env: ['GOPATH=.']

- id: 'Building image'
  name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-challenge:$SHORT_SHA', '.']

- id: 'Pushing image'
  name: 'docker'
  args: ['push', 'gcr.io/$PROJECT_ID/go-challenge:$SHORT_SHA']

- id: 'Replace image name in deployment file - k8s'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      sed 's#brandaogabriel7/go-challenge#gcr.io/$PROJECT_ID/go-challenge:$SHORT_SHA#g' k8s/deployment.yaml > k8s/deployment.yaml
      cat k8s/deployment.yaml;

- id: 'Deploying k8s'
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s']