apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-challenge
spec:
  replicas: 1

  selector:
    matchLabels:
      app: go-challenge

  template:
    metadata:
      labels:
        app: go-challenge
    spec:
      containers:
      - image: brandaogabriel7/go-challenge
        name: go-challenge
    
        ports:
        - containerPort: 8080